[package]
name = "plot"
version = "0.1.0"
authors = ["Muhammad Augi <mohammedaugie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
plotlib = "0.5.0"
ndarray-rand = "0.11.0"